## OVERVIEW
## The two functions makeCacheMatrix and cacheSolve can be used to 
## store and retrieve the inverse of a matrix, instead of calculating 
## it everytime we need the inverse. We assume that the matrix is 
## invertible.

## USING THE FUNCTIONS
## To calculate inverse of a matrix x, first create the list of functions
## using 
## xlistfunc <- makeCacheMatrix(x)
## and next use
## xmatinverse <- cacheSolve(xlistfunc)
## 


## makeCacheMatrix takes as argument a matrix and returns a list of 
## functions. These functions perform the tasks of getting the matrix x,
## setting the matrix x, calculating/setting the inverse of matrix x 
## (denoted by xinv) and getting the matrix inverse.

makeCacheMatrix <- function(x = matrix()) {

  ## Returns a list of functions that can be used to perform operations
  ## on matrix x. If the matrix x is modified using the set function then 
  ## we reset the inverse to NULL. 
  
  xinv <- NULL
  set <- function(y){
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setinv <- function(xinverse) xinv <<- xinverse 
  getinv <- function() xinv
  
  ## returns a list of functions
  
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
  
}


## cacheSolve takes as argument a list of functions that was 
## generated by makeCacheMatrix and returns the inverse of the matrix.
## If the matrix inverse hasn't been calculated before it calculates it.
## Else, it returns a cached inverse with a suitable message.

cacheSolve <- function(x, ...) {
        ## If inverse has been calculated before this function returns 
        ## the cached inverse. If the inverse is NULL then the inverse is 
        ## calculated, cached and returned.
  
  xinv <- x$getinv()

  if(!is.null(xinv)) {
    message("getting cached inverse")
    return(xinv)
  }
  xmatrix <- x$get()
  xinv <- solve(xmatrix, ...)
  x$setinv(xinv)
  xinv
}
